### ISSUE TITLE
Title and Artist info gets lost

### ISSUE THREAD

**Issue by gwi2014** [phrawzty/AudioAddict.bundle#27]
Hi,
thank you very much for this plugin. I'm using this to access di.fm on my BOSE SoundTouch (which has no official support for di.fm see https://www.soundtouch.com/CommunityDetail?_escaped_fragment_/feedtype=SINGLE_QUESTION_DETAIL&dc=SoundTouch&criteria=ALLQUESTIONS&id=90633000000GtfdAAC).
When I listen directly on the browser at di.fm then there is the title and the artist information available. Somehow this gets lost, when I'm using the plugin. Is there any way to fix this?

Regards,
Guido

**Comment by phrawzty** [comment]
Hi Guido,

This is a limitation in Plex itself: the stream is considered to be a single media source, and there is no mechanism to update the media information once it has been loaded.  (Basically, Plex wasn't designed to do streaming radio stations.)

I've included the [necessary code](https://github.com/phrawzty/AudioAddict.bundle/blob/master/Contents/Code/audioaddict.py#L272) for this functionality in my plugin, but until support is added to Plex, it can't be used.

Good luck with your Bose device - I hope it works out for you, even if you don't get the track info.
