### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mabbamOG** [phrawzty/AudioAddict.bundle#30]
the extension isn't working at all.
i tried with a free and a premium account.
the di.fm site states that you need a working premium account to stream with external players, and i do have one.

**Comment by mabbamOG** [comment]
Also, digitally imported is giving me a user code to stream music from a playlist/url.
It's much better to use that than embedding the actual password and username inside the config. At least the code can be changed if the config ends up in the wrong hands...

**Comment by mabbamOG** [comment]
So sorry i posted on the wrong app account!!!

**Comment by phrawzty** [comment]
> So sorry i posted on the wrong app account!!!
This issue was for the mopidy audioaddict extension!

No worries. 😄 If you ever decide to use Plex, feel free to try this plugin out - I assure you that it works (I use it every day).

Cheers!

**Comment by mabbamOG** [comment]
Thanks, unfortunately i only use mopidy because mopidy supports mpd and mpd supports the best/most popular cli music player there is, ncmpcpp. I would gladly use other systems, but the machine i'm playing music on has trouble loading simple webpages, so i basically run everything in the terminal.
