### ISSUE TITLE
[iOS] Couldn't create playback item for this session

### ISSUE THREAD

**Issue by phrawzty** [phrawzty/AudioAddict.bundle#32]
As noted [here](https://forums.plex.tv/discussion/comment/1430444/#Comment_1430444) there appears to be a problem creating the playback item in iOS. When attempting to play a station, the following error is generated: "Couldn't create playback item for this session"

**Comment by sander1** [comment]
If you search for the "Couldn't create playback item for this session" error you'll find that it is not limited to this channel. If your channel works fine on other clients, it's probably not a channel issue, but a Plex/iOS issue.

**Comment by phrawzty** [comment]
Turns out that this was a pretty simple fix. I can confirm that iOS playback is functional on my iPad at least. :)
