### ISSUE TITLE
Not working on 1.8.2.1192-89432618

### ISSUE THREAD

**Issue by pztrn** [phrawzty/AudioAddict.bundle#42]
I can install plugin manually, set preferences, but it isn't showing anywhere at all. I've set up DI.FM listen key in settings.

Anything I can do for getting this plugin working or I should just forget about it (taking in account Channels and other things deprecation in last year)?

**Comment by phrawzty** [comment]
👋 Yes, as channels were deprecated last year, actually using unofficial plugins such as this one is no longer supported by Plex. If you have an older client this plugin still works because the UI is still present, but I don't know how to access it using any recent clients. 😞
